/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as InvestorNameImport } from './routes/investor.$name'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InvestorNameRoute = InvestorNameImport.update({
  id: '/investor/$name',
  path: '/investor/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/investor/$name': {
      id: '/investor/$name'
      path: '/investor/$name'
      fullPath: '/investor/$name'
      preLoaderRoute: typeof InvestorNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investor/$name': typeof InvestorNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investor/$name': typeof InvestorNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/investor/$name': typeof InvestorNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/investor/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/investor/$name'
  id: '__root__' | '/' | '/investor/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestorNameRoute: typeof InvestorNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestorNameRoute: InvestorNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/investor/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/investor/$name": {
      "filePath": "investor.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
